### ISSUE TITLE
Verbose output redirection doesn't work.

### ISSUE THREAD

**Issue by mrplumber** [artemsen/swaykbdd#13]
I tried to pipe `swaykbdd --verbose` output to `awk`, but it seems I/O redirection does not work at all. Tried all sorts of redirection without success. Nothing gets redirected.

**Comment by artemsen** [comment]
This is a buffer effect. Typically the system flushes stdout when a line ends with a `\n` character.
You can disable buffering for swaykbdd using the [stdbuf](https://www.gnu.org/software/coreutils/manual/html_node/stdbuf-invocation.html) utility:
```
stdbuf -o 0 swaykbdd --verbose | awk ...
```

**Comment by mrplumber** [comment]
TIL. That will do for me. Thanks.
