### ISSUE TITLE
xkb_switch_layout dont working when swaykbdd running 

### ISSUE THREAD

**Issue by krabodyan** [artemsen/swaykbdd#14]
when swaykbdd is running, `swaymsg input "*" xkb_switch_layout [...]` command is ignored by sway. 
If I stop swaykbdd, xkb_switch_layout works as intended. 
sway version 1.9
swaykbdd version 1.4

**Comment by artemsen** [comment]
Actually, the command is not ignored.
When `swaymsg ... xkb_switch_layout` is called, the layout will be changed, but after that `swaykbdd` will [call xkb_switch_layout](https://github.com/artemsen/swaykbdd/blob/55435f32299fc19700e6a37260774d3f40c90f9f/src/sway.c#L210) again to set the layout according to its own rules.
You can start `swaykbdd --verbose` to see what happens in runtime.

So, it is not a bug. You should use either `swaykbdd` or another layout management solution, but not both at same time.

**Comment by krabodyan** [comment]
Is there any way to change the layout for layer like rofi when using `swaykbdd`?

**Comment by artemsen** [comment]
I am not sure you can run two different layout managers at the same time.
What does it mean "like rofi"?

**Comment by krabodyan** [comment]
rofi is a dialog window for launching applications. And it is not launched as an application, but as a layer. Because of this, the previous window does not lose focus and the layout does not change

**Comment by artemsen** [comment]
Sorry, I don't know how to solve your problem.
Swaykbdd relies entirely on [changing focus](https://github.com/artemsen/swaykbdd/blob/55435f32299fc19700e6a37260774d3f40c90f9f/src/main.c#L42).

**Comment by krabodyan** [comment]
Thank you for your program and your help
