### ISSUE TITLE
Per tab layout doesn't work with Firefox Developer Edition

### ISSUE THREAD

**Issue by crabvk** [artemsen/swaykbdd#8]
Thank you for the feature.
I see you [hardcoded](https://github.com/artemsen/swaykbdd/blob/9bd3680e94fb0e41ffe75c83206c65401ab15f15/src/sway.c#L244) `add_id`s. The problem is Firefox Developer Edition has `add_id` equal to `firefoxdeveloperedition`.

**Comment by artemsen** [comment]
Done!
Use something like `swaykbdd --tabapps=firefoxdeveloperedition,firefox,chrome`.
