### ISSUE TITLE
Notification from window with other language, changes the language of currently typing window

### ISSUE THREAD

**Issue by christ4k** [artemsen/swaykbdd#9]
With `1.2` update when a notification arrives from a window that had another language from the current one, I start typing in the language of the first window.
I downgraded the package to `1.1` and everything works as usual

**Comment by artemsen** [comment]
Could you please describe the steps to reproduce the bug?

**Comment by artemsen** [comment]
I reproduced this, it's definitely a bug.

**Comment by christ4k** [comment]
That was quick. I'll wait for the next release to install it
